/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.skillforge;

import java.util.List;

import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Farah
 */
public class BrowseFrame extends javax.swing.JFrame {

    Student Student = (Student) Manager.getCurrentUser();
    List<Course> availableCourses = new JsonDatabaseManager().getAllCourses();
    private boolean isRefreshAfterEnrollment = false;

    public BrowseFrame() {
        initComponents();
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        EnrollBtn.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SearchBar = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        EnrollBtn = new javax.swing.JButton();
        GobackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Available Courses");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Name", "Description", "Instructor", "Number Of  Lessons"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });

        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        EnrollBtn.setText("Enroll");
        EnrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollBtnActionPerformed(evt);
            }
        });

        GobackBtn.setText("Go Back");
        GobackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GobackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(204, 204, 204)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(143, 143, 143))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(EnrollBtn, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(SearchBtn, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addContainerGap(105, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(GobackBtn)
                                                .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(GobackBtn)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(SearchBtn))
                                                .addGap(3, 3, 3)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(29, 29, 29)
                                                                .addComponent(EnrollBtn))
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GobackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GobackBtnActionPerformed
        this.dispose();
        new StudentDashboardFrame().setVisible(true);
    }//GEN-LAST:event_GobackBtnActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchBarActionPerformed

    }// GEN-LAST:event_SearchBarActionPerformed

    private void EnrollBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course to enroll.", "Selection Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        String courseTitle = (String) jTable1.getValueAt(selectedRow, 0);
        Course selectedCourse = null;
        for (Course course : availableCourses) {
            if (course.getTitle().equals(courseTitle)) {
                selectedCourse = course;
                break;
            }
        }

        if (selectedCourse == null) {
            JOptionPane.showMessageDialog(this, "Selected course not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to Enroll in " + selectedCourse.getTitle() + "?",
                "Confirm Enroll",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String enrolledCourseTitle = selectedCourse.getTitle();

        selectedCourse.enrollStudent(Student);

        JOptionPane.showMessageDialog(this, "Successfully enrolled in " + enrolledCourseTitle + "!",
                "Enrollment Successful", JOptionPane.INFORMATION_MESSAGE);
                isRefreshAfterEnrollment = true;

        String currentSearch = SearchBar.getText().trim();
        if (!currentSearch.isEmpty()) {
            loadAvaiablecoursesToTable(currentSearch);
        }
         isRefreshAfterEnrollment = false;
    }// GEN-LAST:event_EnrollBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchBtnActionPerformed
        String searchText = SearchBar.getText().trim();
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a search term.", "Input Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        loadAvaiablecoursesToTable(searchText);
    }// GEN-LAST:event_SearchBtnActionPerformed

    private void loadAvaiablecoursesToTable(String searchText) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        boolean flag = false;
        if (availableCourses.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Course File is Empty", "ERROR", JOptionPane.ERROR_MESSAGE);
            EnrollBtn.setVisible(false);
            return;
        }
         // if condition to check only for approved courses
        for (Course course : availableCourses) {
            if (course.isStudentEnrolled(Student)) {
                continue;
            }
            List<Instructor> instructors = new JsonDatabaseManager().getAllInstructors();
            String instructorName = "Unknown";
            for (Instructor instructor : instructors) {
                if (instructor.getUserId().equals(course.getInstructorId())) {
                    instructorName = instructor.getUsername();
                    break;
                }
            }
            if (course.getTitle().toLowerCase().contains(searchText.toLowerCase())
                    || course.getDescription().toLowerCase().contains(searchText.toLowerCase())) {
                Object[] row = {
                    course.getTitle(),
                    course.getDescription(),
                    instructorName,
                    course.getLessons().size()
                };
                model.addRow(row);
                flag = true;
            }
        }
        if (flag) {
            jTable1.setVisible(true);
            jScrollPane1.setVisible(true);
            EnrollBtn.setVisible(true);
            jScrollPane1.revalidate();
            jScrollPane1.repaint();
            jTable1.revalidate();
            jTable1.repaint();
            this.revalidate();
            this.repaint();
        } else {
                if (!isRefreshAfterEnrollment) {
            JOptionPane.showMessageDialog(this, "No available courses found matching your search.", "No Results", JOptionPane.INFORMATION_MESSAGE);
        }
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        EnrollBtn.setVisible(false);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrowseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnrollBtn;
    private javax.swing.JButton GobackBtn;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
