/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.skillforge;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Insructor extends javax.swing.JFrame {

    Instructor instructor = (Instructor) Manager.getCurrentUser();
    List<Course> createdCourses = instructor.getCreatedCourseObjects();
    JsonDatabaseManager dbManager = new JsonDatabaseManager();

    public Insructor() {
        initComponents();
        LoadCreatedCourses();
        jLabel2.setVisible(false);
        jScrollPane4.setVisible(false);
        LessonsTable.setVisible(false);
        AddLessonBtn.setVisible(false);
        RemoveLessonBtn.setVisible(false);
        SaveBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        InstructorName = new javax.swing.JLabel();
        InstructorId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EnrolledStudentBtn = new javax.swing.JButton();
        ViewLessonsBtn = new javax.swing.JButton();
        CreateNewCourseBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        RemoveCourseBtn = new javax.swing.JButton();
        AddLessonBtn = new javax.swing.JButton();
        RemoveLessonBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        CourseTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        LessonsTable = new javax.swing.JTable();
        SaveBtn = new javax.swing.JButton();
        CourseSaveBtn1 = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InstructorName.setText(instructor.getUsername());

        InstructorId.setText(instructor.getUserId());

        jLabel1.setText("Created Courses");

        EnrolledStudentBtn.setText("View Enrolled Students");
        EnrolledStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrolledStudentBtnActionPerformed(evt);
            }
        });

        ViewLessonsBtn.setText("View Lessons");
        ViewLessonsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLessonsBtnActionPerformed(evt);
            }
        });

        CreateNewCourseBtn.setText("Create New Course");
        CreateNewCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewCourseBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Related Lessons ");

        RemoveCourseBtn.setText("Remove Course");
        RemoveCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveCourseBtnActionPerformed(evt);
            }
        });

        AddLessonBtn.setText("Add Lesson");
        AddLessonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLessonBtnActionPerformed(evt);
            }
        });

        RemoveLessonBtn.setText("Remove Lesson");
        RemoveLessonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveLessonBtnActionPerformed(evt);
            }
        });

        CourseTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                },
                new String[]{
                    "ID", "Title", "Description"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        CourseTable.setColumnSelectionAllowed(true);
        CourseTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(CourseTable);
        CourseTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        LessonsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "ID", "Title", "Content", "optional resources"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane4.setViewportView(LessonsTable);

        SaveBtn.setText("Save Changes");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        CourseSaveBtn1.setText("Save Changes");
        CourseSaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseSaveBtn1ActionPerformed(evt);
            }
        });

        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(LogOutBtn))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(InstructorName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(InstructorId, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(29, 29, 29))
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(37, 37, 37)))
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(AddLessonBtn)
                                                                                        .addComponent(EnrolledStudentBtn)
                                                                                        .addComponent(RemoveLessonBtn)
                                                                                        .addComponent(SaveBtn)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(13, 13, 13)
                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(CourseSaveBtn1)
                                                                                                        .addComponent(ViewLessonsBtn))))))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RemoveCourseBtn)
                                                                        .addComponent(CreateNewCourseBtn))))
                                                .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(InstructorName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(InstructorId)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(CreateNewCourseBtn)
                                                        .addComponent(EnrolledStudentBtn))
                                                .addGap(58, 58, 58)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(ViewLessonsBtn)
                                                        .addComponent(RemoveCourseBtn))
                                                .addGap(42, 42, 42)
                                                .addComponent(CourseSaveBtn1)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(38, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(51, 51, 51)
                                                .addComponent(AddLessonBtn)
                                                .addGap(27, 27, 27)
                                                .addComponent(RemoveLessonBtn)
                                                .addGap(31, 31, 31)
                                                .addComponent(SaveBtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LogOutBtn)
                                                .addGap(60, 60, 60))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadCreatedCourses() {
        DefaultTableModel model = (DefaultTableModel) CourseTable.getModel();
        model.setRowCount(0);
        for (Course course : createdCourses) {
            String CourseId = course.getCourseId();
            String CourseTitle = course.getTitle();
            String CourseDescription = course.getDescription();
            model.addRow(new Object[]{CourseId, CourseTitle, CourseDescription});
        }
    }

    private void EnrolledStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = CourseTable.getSelectedRow();
        if (selectedRow >= 0 && createdCourses != null) {
            Course selectedCourse = createdCourses.get(selectedRow);
            if (selectedCourse.getStudentIDs().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No students enrolled in this course.");
                return;
            }
            ViewEnrolledStudents viewEnrolledStudentsFrame = new ViewEnrolledStudents(selectedCourse);
            viewEnrolledStudentsFrame.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a course first.");
        }

    }

    private void CreateNewCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewCourseBtnActionPerformed
        CreateCourse createCourseFrame = new CreateCourse();

        createCourseFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CreateNewCourseBtnActionPerformed

    private void RemoveCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to Remove Course?",
                "Confirm Remove Course",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        } else {
            int selectedRow = CourseTable.getSelectedRow();
            if (selectedRow >= 0) {
                Course courseToRemove = createdCourses.get(selectedRow);
                courseToRemove.DeleteCourse();
                createdCourses.remove(selectedRow);
                LoadCreatedCourses();
            }
        }
    }//GEN-LAST:event_RemoveCourseBtnActionPerformed

    private void ViewLessonsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLessonsBtnActionPerformed
        jLabel2.setVisible(true);
        jScrollPane4.setVisible(true);
        LessonsTable.setVisible(true);
        AddLessonBtn.setVisible(true);
        RemoveLessonBtn.setVisible(true);
        SaveBtn.setVisible(true);

        this.getContentPane().revalidate();
        this.getContentPane().repaint();

        int selectedRow = CourseTable.getSelectedRow();
        if (selectedRow >= 0) {
            Course selectedCourse = createdCourses.get(selectedRow);
            if (selectedCourse.getLessons().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No lessons available for this course.");
                DefaultTableModel model = (DefaultTableModel) LessonsTable.getModel();
                model.setRowCount(0);
                RemoveLessonBtn.setVisible(false);
                SaveBtn.setVisible(false);
                return;
            } else {
                List<Lesson> lessons = selectedCourse.getLessons();
                DefaultTableModel model = (DefaultTableModel) LessonsTable.getModel();
                model.setRowCount(0);
                for (Lesson lesson : lessons) {
                    String lessonId = lesson.getLessonId();
                    String lessonTitle = lesson.getTitle();
                    String lessonContent = lesson.getContent();
                    List<String> resources = lesson.getResources();
                    String optionalResources;
                    if (resources.isEmpty()) {
                        optionalResources = "";
                    } else {
                        optionalResources = String.join(", ", resources);
                    }
                    model.addRow(new Object[]{lessonId, lessonTitle, lessonContent, optionalResources});
                }
                RemoveLessonBtn.setVisible(true);
                SaveBtn.setVisible(true);
            }
        }
    }//GEN-LAST:event_ViewLessonsBtnActionPerformed

    private void AddLessonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLessonBtnActionPerformed
        int selectedRow = CourseTable.getSelectedRow();
        if (selectedRow >= 0) {
            Course selectedCourse = createdCourses.get(selectedRow);
            AddLesson addLessonFrame = new AddLesson(selectedCourse);
            addLessonFrame.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_AddLessonBtnActionPerformed

    private void RemoveLessonBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to Remove Lesson?",
                "Confirm Remove Lesson",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        } else {
            int selectedRow = LessonsTable.getSelectedRow();
            if (selectedRow >= 0) {
                int courseRow = CourseTable.getSelectedRow();
                Course selectedCourse = createdCourses.get(courseRow);
                List<Lesson> lessons = selectedCourse.getLessons();
                Lesson lessonToRemove = lessons.get(selectedRow);
                selectedCourse.removeLesson(lessonToRemove);
                DefaultTableModel model = (DefaultTableModel) LessonsTable.getModel();
                model.removeRow(selectedRow);
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Lesson removed successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_RemoveLessonBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to Save Changes to Lesson?",
                "Confirm Save Changes",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        } else {
            int courseRow = CourseTable.getSelectedRow();
            if (courseRow >= 0) {
                Course selectedCourse = createdCourses.get(courseRow);
                DefaultTableModel model = (DefaultTableModel) LessonsTable.getModel();
                for (int i = 0; i < model.getRowCount(); i++) {
                    String lessonId = (String) model.getValueAt(i, 0);
                    String lessonTitle = (String) model.getValueAt(i, 1);
                    String lessonContent = (String) model.getValueAt(i, 2);
                    String lessonOptionalResourses = (String) model.getValueAt(i, 3);
                    List<String> resourcesList = new ArrayList<>();
                    if (lessonOptionalResourses != null
                            && !lessonOptionalResourses.isEmpty()
                            && !lessonOptionalResourses.equals("No resources")) {

                        String[] resourcesArray = lessonOptionalResourses.split(", ");
                        if (resourcesArray.length > 0 && !resourcesArray[0].isEmpty()) {
                            for (String resource : resourcesArray) {
                                if (!resource.trim().isEmpty()) {
                                    resourcesList.add(resource.trim());
                                }
                            }
                        }
                    }
                    Lesson lessonToUpdate = null;
                    for (Lesson lesson : selectedCourse.getLessons()) {
                        if (lesson.getLessonId().equals(lessonId)) {
                            lessonToUpdate = lesson;
                            break;
                        }
                    }
                    if (lessonToUpdate != null) {
                        lessonToUpdate.setTitle(lessonTitle);
                        lessonToUpdate.setContent(lessonContent);
                        lessonToUpdate.getResources().clear();
                        lessonToUpdate.setResource(resourcesList);
                        selectedCourse.updateLesson(lessonToUpdate);

                    }
                }
                dbManager.updateCourse(selectedCourse);
                javax.swing.JOptionPane.showMessageDialog(this, "Lesson Updated successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a lesson to update.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void CourseSaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to Save Changes to Course?",
                "Confirm Save Changes",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        } else {
            DefaultTableModel model = (DefaultTableModel) CourseTable.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                String courseId = (String) model.getValueAt(i, 0);
                String courseTitle = (String) model.getValueAt(i, 1);
                String courseDescription = (String) model.getValueAt(i, 2);
                Course courseToUpdate = null;
                for (Course course : createdCourses) {
                    if (course.getCourseId().equals(courseId)) {
                        courseToUpdate = course;
                        break;
                    }
                }
                if (courseToUpdate != null) {
                    courseToUpdate.setTitle(courseTitle);
                    courseToUpdate.setDescription(courseDescription);
                    dbManager.updateCourse(courseToUpdate);
                }
            }
        }

    }//GEN-LAST:event_CourseSaveBtn1ActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to Log Out?",
                "Confirm Log Out",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        } else {
            this.dispose();
            Login loginFrame = new Login();
            loginFrame.setVisible(true);
        }

    }//GEN-LAST:event_LogOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insructor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLessonBtn;
    private javax.swing.JButton CourseSaveBtn1;
    private javax.swing.JTable CourseTable;
    private javax.swing.JButton CreateNewCourseBtn;
    private javax.swing.JButton EnrolledStudentBtn;
    private javax.swing.JLabel InstructorId;
    private javax.swing.JLabel InstructorName;
    private javax.swing.JTable LessonsTable;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton RemoveCourseBtn;
    private javax.swing.JButton RemoveLessonBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton ViewLessonsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
