/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.skillforge;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Farah
 */
public class QuizFrame extends javax.swing.JFrame {
    Lesson lesson;
    Quiz quiz;
    Student student;
    public QuizFrame(Lesson lesson) {
        this.lesson = lesson;
        this.quiz = lesson.getQuiz();
        student =(Student) Manager.getCurrentUser();
        initComponents();
        YourAnswer1.setVisible(false);
        CorrectAnswer1.setVisible(false);
        YourAnswer2.setVisible(false);
        CorrectAnswer2.setVisible(false);
        YourAnswer3.setVisible(false);
        CorrectAnswer3.setVisible(false);
        YourAnswer4.setVisible(false);
        CorrectAnswer4.setVisible(false);
        YourAnswer5.setVisible(false);
        CorrectAnswer5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        YourAnswer2 = new javax.swing.JLabel();
        CorrectAnswer1 = new javax.swing.JLabel();
        SubmitBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        YourAnswer1 = new javax.swing.JLabel();
        CorrectAnswer2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        YourAnswer3 = new javax.swing.JLabel();
        CorrectAnswer3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        YourAnswer4 = new javax.swing.JLabel();
        CorrectAnswer4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        YourAnswer5 = new javax.swing.JLabel();
        CorrectAnswer5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Quiz on " + lesson.getTitle());

        jLabel2.setText("Remaining attempts : " + (quiz.getMaxNumberofAttempts() - quiz.getStudentAttempts()));

        jLabel3.setText("Bellow are the questions you are required to answer in order to complete this lesson");

        jButton3.setText("Go Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Q1:");

        jLabel5.setText(quiz.getAllQuestions().get(0).getQuestionText());

        YourAnswer2.setText("Your Answer :");

        CorrectAnswer1.setText("Correct Answer :" + quiz.getAllQuestions().get(0).getCorrectAnswer());

        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Q2:");

        jLabel9.setText(quiz.getAllQuestions().get(1).getQuestionText());

        YourAnswer1.setText("Your Answer :");

        CorrectAnswer2.setText("Correct Answer :" + quiz.getAllQuestions().get(1).getCorrectAnswer());

        jLabel12.setText("Q4:");

        jLabel13.setText(quiz.getAllQuestions().get(2).getQuestionText());

        YourAnswer3.setText("Your Answer :");

        CorrectAnswer3.setText("Correct Answer :" + quiz.getAllQuestions().get(2).getCorrectAnswer());

        jLabel16.setText("Q3:");

        jLabel17.setText(quiz.getAllQuestions().get(3).getQuestionText());

        YourAnswer4.setText("Your Answer :");

        CorrectAnswer4.setText("Correct Answer :" + quiz.getAllQuestions().get(3).getCorrectAnswer());

        jLabel20.setText("Q5:");

        jLabel21.setText(quiz.getAllQuestions().get(4).getQuestionText());

        YourAnswer5.setText("Your Answer :");

        CorrectAnswer5.setText("Correct Answer :" + quiz.getAllQuestions().get(4).getCorrectAnswer());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText(quiz.getAllQuestions().get(0).getOptionAt(0));
      
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText( quiz.getAllQuestions().get(0).getOptionAt(1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText( quiz.getAllQuestions().get(0).getOptionAt(2));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText( quiz.getAllQuestions().get(0).getOptionAt(3));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText( quiz.getAllQuestions().get(1).getOptionAt(0));

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText( quiz.getAllQuestions().get(1).getOptionAt(1));

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText( quiz.getAllQuestions().get(1).getOptionAt(2));

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText( quiz.getAllQuestions().get(1).getOptionAt(3));

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setText( quiz.getAllQuestions().get(2).getOptionAt(0));

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setText( quiz.getAllQuestions().get(2).getOptionAt(1));

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setText( quiz.getAllQuestions().get(2).getOptionAt(2));

        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setText( quiz.getAllQuestions().get(2).getOptionAt(3));

        buttonGroup4.add(jRadioButton13);
        jRadioButton13.setText( quiz.getAllQuestions().get(3).getOptionAt(0));

        buttonGroup4.add(jRadioButton14);
        jRadioButton14.setText( quiz.getAllQuestions().get(3).getOptionAt(1));

        buttonGroup4.add(jRadioButton15);
        jRadioButton15.setText( quiz.getAllQuestions().get(3).getOptionAt(2));

        buttonGroup4.add(jRadioButton16);
        jRadioButton16.setText( quiz.getAllQuestions().get(3).getOptionAt(3));

        buttonGroup5.add(jRadioButton17);
        jRadioButton17.setText( quiz.getAllQuestions().get(4).getOptionAt(0));

        buttonGroup5.add(jRadioButton18);
        jRadioButton18.setText( quiz.getAllQuestions().get(4).getOptionAt(1));

        buttonGroup5.add(jRadioButton19);
        jRadioButton19.setText( quiz.getAllQuestions().get(4).getOptionAt(2));

        buttonGroup5.add(jRadioButton20);
        jRadioButton20.setText( quiz.getAllQuestions().get(4).getOptionAt(3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(SubmitBtn))
                    .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YourAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CorrectAnswer2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CorrectAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YourAnswer1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YourAnswer4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YourAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CorrectAnswer3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CorrectAnswer4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YourAnswer5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CorrectAnswer5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jRadioButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addGap(18, 18, 18)
                .addComponent(YourAnswer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorrectAnswer1)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8))
                .addGap(7, 7, 7)
                .addComponent(YourAnswer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorrectAnswer2)
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton12))
                .addGap(18, 18, 18)
                .addComponent(YourAnswer3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorrectAnswer3)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton13)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(YourAnswer4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorrectAnswer4)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton17)
                    .addComponent(jRadioButton18)
                    .addComponent(jRadioButton19)
                    .addComponent(jRadioButton20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YourAnswer5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorrectAnswer5)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(SubmitBtn))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        YourAnswer1.setVisible(true);
        YourAnswer1.setText("Your Answer :" + getSelectedButtonText(buttonGroup1,jRadioButton1,jRadioButton2,jRadioButton3,jRadioButton4));
        CorrectAnswer1.setVisible(true);
        YourAnswer2.setVisible(true);
        YourAnswer2.setText("Your Answer :"+ getSelectedButtonText(buttonGroup2,jRadioButton5,jRadioButton6,jRadioButton7,jRadioButton8));
        CorrectAnswer2.setVisible(true);
        YourAnswer3.setVisible(true);
        YourAnswer3.setText("Your Answer :"+ getSelectedButtonText(buttonGroup3,jRadioButton9,jRadioButton10,jRadioButton11,jRadioButton12));
        CorrectAnswer3.setVisible(true);
        YourAnswer4.setVisible(true);
        YourAnswer4.setText("Your Answer :" + getSelectedButtonText(buttonGroup4,jRadioButton13,jRadioButton14,jRadioButton15,jRadioButton16));
        CorrectAnswer4.setVisible(true);
        YourAnswer5.setVisible(true);
        YourAnswer5.setText("Your Answer :"+ getSelectedButtonText(buttonGroup5,jRadioButton17,jRadioButton18,jRadioButton19,jRadioButton20));
        CorrectAnswer5.setVisible(true);
        if (quiz.getStudentAttempts() < quiz.getMaxNumberofAttempts()) {
            quiz.incrementAttempts();
            
            if (getSelectedButtonText(buttonGroup1,jRadioButton1,jRadioButton2,jRadioButton3,jRadioButton4).equals(quiz.getAllQuestions().get(0).getCorrectAnswer())) {
               quiz.incrementScore();
            }
            if (getSelectedButtonText(buttonGroup2,jRadioButton5,jRadioButton6,jRadioButton7,jRadioButton8).equals(quiz.getAllQuestions().get(1).getCorrectAnswer())) {
                quiz.incrementScore();
            }
            if (getSelectedButtonText(buttonGroup3,jRadioButton9,jRadioButton10,jRadioButton11,jRadioButton12).equals(quiz.getAllQuestions().get(2).getCorrectAnswer())) {
                 quiz.incrementScore();
            }
            if (getSelectedButtonText(buttonGroup4,jRadioButton13,jRadioButton14,jRadioButton15,jRadioButton16).equals(quiz.getAllQuestions().get(3).getCorrectAnswer())) {
                 quiz.incrementScore();
            }
            if (getSelectedButtonText(buttonGroup5,jRadioButton17,jRadioButton18,jRadioButton19,jRadioButton20).equals(quiz.getAllQuestions().get(4).getCorrectAnswer())) {
                 quiz.incrementScore();
            }
            if(quiz.isPassed()) {
                lesson.markAsCompleted(student);
            }
              JOptionPane.showMessageDialog(this, "You scored" + quiz.getScore() + " out of " + quiz.getAllQuestions().size()); 
        }
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        LessonFrame lessonFrame = new LessonFrame(lesson);
        lessonFrame.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

       private String getSelectedButtonText(ButtonGroup group, JRadioButton... buttons) {
        for (JRadioButton button : buttons) {
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return "No Answer Selected";
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizFrame(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CorrectAnswer1;
    private javax.swing.JLabel CorrectAnswer2;
    private javax.swing.JLabel CorrectAnswer3;
    private javax.swing.JLabel CorrectAnswer4;
    private javax.swing.JLabel CorrectAnswer5;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel YourAnswer1;
    private javax.swing.JLabel YourAnswer2;
    private javax.swing.JLabel YourAnswer3;
    private javax.swing.JLabel YourAnswer4;
    private javax.swing.JLabel YourAnswer5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
