/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.skillforge;

import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Farah
 */
public class StudentDashboardFrame extends javax.swing.JFrame {

    Student Student;
    List<Course> availableCourses;
    List<Course> enrolledCourses;
    List<Lesson> CompletedLessons;

    public StudentDashboardFrame() {
        Student = (Student) Manager.getCurrentUser();
        availableCourses = new JsonDatabaseManager().getAllCourses();
        enrolledCourses = Student.getEnrolledCourseObjects();
        CompletedLessons = Student.getCompletedLessons();
        initComponents();
        LoadEnrolledCoursesTolist();
        LoadAvailableCoursesToList();
        LessonList.setVisible(false);
        LessonFrameBtn.setVisible(false);
    }

    private void initializeListModels() {
        DefaultListModel<String> enrolledModel = new DefaultListModel<>();
        DefaultListModel<String> availableModel = new DefaultListModel<>();
        DefaultListModel<String> lessonModel = new DefaultListModel<>();

        EnrolledCoursesList.setModel(enrolledModel);
        AvailableCoursesList.setModel(availableModel);
        LessonList.setModel(lessonModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EnrolledCoursesList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        AvailableCoursesList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        UnenrollBtn = new javax.swing.JButton();
        EnrollBtn = new javax.swing.JButton();
        BrowseBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LessonList = new javax.swing.JList<>();
        ViewLessonsBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        LessonFrameBtn = new javax.swing.JButton();
        GenerateCertificateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        EnrolledCoursesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        EnrolledCoursesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(EnrolledCoursesList);

        AvailableCoursesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        AvailableCoursesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(AvailableCoursesList);

        jLabel3.setText("Available Courses");

        jLabel4.setText("Enrolled Courses");

        UnenrollBtn.setText("UnEnroll");
        UnenrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnenrollBtnActionPerformed(evt);
            }
        });

        EnrollBtn.setText("Enroll");
        EnrollBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollBtnActionPerformed(evt);
            }
        });

        BrowseBtn.setText("Browse");
        BrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Lessons");

        LessonList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        LessonList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(LessonList);

        ViewLessonsBtn.setText("View Lessons");
        ViewLessonsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLessonsBtnActionPerformed(evt);
            }
        });

        LogOutBtn.setText("Log out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        LessonFrameBtn.setText("Start Lesson");
        LessonFrameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LessonFrameBtnActionPerformed(evt);
            }
        });

        GenerateCertificateBtn.setText("Generate Certificate ");
        GenerateCertificateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateCertificateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UnenrollBtn)
                                    .addComponent(ViewLessonsBtn)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LogOutBtn)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EnrollBtn)
                                        .addComponent(BrowseBtn)))))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LessonFrameBtn)
                                    .addComponent(GenerateCertificateBtn))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EnrollBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BrowseBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UnenrollBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ViewLessonsBtn)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LessonFrameBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GenerateCertificateBtn)
                        .addGap(27, 27, 27)
                        .addComponent(LogOutBtn)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnenrollBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to Unenroll From Course?",
                "Confirm Unenroll",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        } else {
            int selected = EnrolledCoursesList.getSelectedIndex();
            if (selected != -1) {
                Course courseToUnenroll = enrolledCourses.get(selected);
                courseToUnenroll.unenrollStudent(Student);
                enrolledCourses = Student.getEnrolledCourseObjects();
                LoadEnrolledCoursesTolist();
                LoadAvailableCoursesToList();
                LessonList.setVisible(false);
                DefaultListModel<String> emptyModel = new DefaultListModel<>();
                LessonList.setModel(emptyModel);
                LessonFrameBtn.setVisible(false);
                JOptionPane.showMessageDialog(this, "Successfully unenrolled from course!", "Success", JOptionPane.INFORMATION_MESSAGE);
                

            } else {
                JOptionPane.showMessageDialog(this, "Please select a course to unenroll.");
            }
        }
    }                                           

    private void EnrollBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to Enroll in Course?",
                "Confirm Enroll",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        } else {
            int selected = AvailableCoursesList.getSelectedIndex();
            if (selected != -1) {
                Course courseToEnroll = availableCourses.get(selected);
                courseToEnroll.enrollStudent(Student);
                enrolledCourses = Student.getEnrolledCourseObjects();
                LoadEnrolledCoursesTolist();
                LoadAvailableCoursesToList();

                JOptionPane.showMessageDialog(this, "Successfully enrolled in course!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Please select a course to enroll.");
            }
        }
    }                                         

    private void BrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseBtnActionPerformed
        BrowseFrame browseFrame = new BrowseFrame();
        browseFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BrowseBtnActionPerformed

    private void LessonFrameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LessonFrameBtnActionPerformed
        int selected = LessonList.getSelectedIndex();
        if (selected != -1) {
            Lesson selectedLesson = Student.getEnrolledCourseObjects().get(EnrolledCoursesList.getSelectedIndex()).getLessons().get(selected);
            LessonFrame lessonFrame = new LessonFrame(selectedLesson);
            lessonFrame.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a lesson to start.");
        }
    }//GEN-LAST:event_LessonFrameBtnActionPerformed

    private void GenerateCertificateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateCertificateBtnActionPerformed
   this.dispose();
// Call Certificate Frame
    }//GEN-LAST:event_GenerateCertificateBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to Log Out?",
                "Confirm Log Out",
                JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        } else {
            this.dispose();
            Login loginFrame = new Login();
            loginFrame.setVisible(true);
        }
    }                                         

    private void ViewLessonsBtnActionPerformed(java.awt.event.ActionEvent evt) {
       // addLessonProgress(String courseId, String LessonId);
        LessonList.setVisible(true);
        int selected = EnrolledCoursesList.getSelectedIndex();
        if (selected != -1) {
            Course selectedCourse = Student.getEnrolledCourseObjects().get(selected);
            List<Lesson> lessons = selectedCourse.getLessons();
            DefaultListModel<String> model = new DefaultListModel<>();
            CompletedLessons = Student.getCompletedLessons();
            for (Lesson lesson : lessons) {
                boolean isCompleted = false;
                for (Lesson completed : CompletedLessons) {
                    if (completed.getLessonId().equals(lesson.getLessonId())) {
                        isCompleted = true;
                        break;
                    }
                }
                String status = isCompleted ? "✓ " : "○ ";
                model.addElement(status + lesson.getTitle());
            }

            LessonList.setModel(model);
            LessonList.setVisible(true);
            LessonFrameBtn.setVisible(true);

              LessonList.revalidate();
        LessonList.repaint();
        jScrollPane3.revalidate();
        jScrollPane3.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a course to view lessons.");
        }
    }

    private void LoadEnrolledCoursesTolist() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Course course : enrolledCourses) {
            model.addElement(course.getTitle());
        }
        EnrolledCoursesList.setModel(model);
          EnrolledCoursesList.revalidate();
    EnrolledCoursesList.repaint();
    jScrollPane2.revalidate();
    jScrollPane2.repaint();
    }

    private void LoadAvailableCoursesToList() {
        DefaultListModel<String> model = new DefaultListModel<>();

        for (Course course : availableCourses) {
            if(course.isApproved()){
            if (!course.isStudentEnrolled(Student)) {
                model.addElement(course.getTitle());
            }
        }
    }
        AvailableCoursesList.setModel(model);
          AvailableCoursesList.revalidate();
    AvailableCoursesList.repaint();
    jScrollPane2.revalidate();
    jScrollPane2.repaint();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AvailableCoursesList;
    private javax.swing.JButton BrowseBtn;
    private javax.swing.JButton EnrollBtn;
    private javax.swing.JList<String> EnrolledCoursesList;
    private javax.swing.JButton GenerateCertificateBtn;
    private javax.swing.JButton LessonFrameBtn;
    private javax.swing.JList<String> LessonList;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton UnenrollBtn;
    private javax.swing.JButton ViewLessonsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
