/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.skillforge;

import java.util.List;

/**
 *
 * @author User
 */
public class ViewEnrolledStudents extends javax.swing.JFrame {
    private Course selectedCourse;
    private JsonDatabaseManager dbManager = new JsonDatabaseManager();
    /**
     * Creates new form ViewEnrolledStudents
     * @param selectedCourse 
     */
    public ViewEnrolledStudents(Course selectedCourse) {
        this.selectedCourse = selectedCourse;
        initComponents();
    LoadEnrolldStudentstoTable();
    
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        GoBackBtn = new javax.swing.JButton();
        // UnEnrollBtn = new javax.swing.JButton(); 

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "ID", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        GoBackBtn.setText("Go Back");
        GoBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackBtnActionPerformed(evt);
            }
        });

        // UnEnrollBtn.setText("UnEnroll");
        // UnEnrollBtn.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) { 
        //         UnEnrollBtnActionPerformed(evt); 
        //     } 
        // }); 

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoBackBtn)
                .addContainerGap(14, Short.MAX_VALUE))
            // .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup() 
            //     .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            //     .addComponent(UnEnrollBtn) 
            //     .addGap(20, 20, 20)) 
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(GoBackBtn)))
                // .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED) 
                // .addComponent(UnEnrollBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void LoadEnrolldStudentstoTable() {
        try {
            List<Student> enrolledStudents = selectedCourse.getStudentsObjects();
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); 
            for (Student student : enrolledStudents) {
                Object[] row = {student.getUsername(), student.getUserId(), student.getEmail()};
                model.addRow(row);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading enrolled students: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

    }
}
    
    private void GoBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackBtnActionPerformed
        this.dispose();
        new Insructor().setVisible(true);
    }//GEN-LAST:event_GoBackBtnActionPerformed

    // private void UnEnrollBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnEnrollBtnActionPerformed
    //    int selectedRow = jTable1.getSelectedRow();
    //     if (selectedRow >= 0) {
    //         String studentId = (String) jTable1.getValueAt(selectedRow, 1);
    //         try {
    //             dbManager.deleteStudent(studentId);
    //             LoadEnrolldStudentstoTable(); 
    //             javax.swing.JOptionPane.showMessageDialog(this, "Student unenrolled successfully.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    //         } catch (Exception e) {
    //             javax.swing.JOptionPane.showMessageDialog(this, "Error unenrolling student: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    //         }
    //     } else {
    //         javax.swing.JOptionPane.showMessageDialog(this, "Please select a student to unenroll.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    //     }
    // }//GEN-LAST:event_UnEnrollBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEnrolledStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEnrolledStudents(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoBackBtn;
    // private javax.swing.JButton UnEnrollBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}